= Docker Images for vrtlmod

== Prerequisites

In addition to a regular Docker installation, `buildx` is required for building the vrtlmod images.

Dependencies::
[,bash]
----
apt install docker-buildx-plugin
----

== Container/Image Types

=== `vrtlmod-base`

The `vrtlmod-base` image contains an installation of LLVM patched and built with `vrtlmod`. Furthermore, the image is pruned of LLVM build artifacts and source-code.

NOTE: `vrtlmod-base` is intended to be used as a "standalone" compiler container.

=== `vrtlmod-dev`

t.b.d.


== Use

=== Pulling prebuilt images

Check our https://hub.docker.com/r/tumeda/[DockerHub] for the latest images and supported OS/LLVM versions:

* https://hub.docker.com/r/tumeda/vrtlmod-base/tags[`vrtlmod-base`]
** debian:stable image:https://img.shields.io/docker/v/tumeda/vrtlmod-base/latest-default-debian-stable["tumeda/vrtlmod-base", link="https://img.shields.io/docker/v/tumeda/vrtlmod-base/latest-default-debian-stable"]

Example commands to pull an image from the registry::
[,bash]
----
docker pull tumeda/vrtlmod-base:latest-default-debian-stable
----

=== Building Images

==== Local

You can build the images locally as follows::
[,bash]
----
cd path/to/vrtlmod/clone
source docker/.env

# Build vrtlmod-base image
docker buildx build . -f docker/Dockerfile \
                      --tag tumeda/vrtlmod-base:latest-default-debian-stable \
                      --target vrtlmod-base \
                      --build-arg BASE_IMAGE=debian:stable \
                      --build-arg workspace_dir=. \
                      --build-arg ENV_LLVM_FROM_SOURCE=${ENV_LLVM_FROM_SOURCE} \
                      --build-arg ENV_LLVM_VERSION=${ENV_LLVM_VERSION} \
                      --build-arg ENV_BUILD_CONFIG=${ENV_BUILD_CONFIG} \
                      --build-arg ENV_BUILD_CXX_STANDARD=${ENV_BUILD_CXX_STANDARD}
----

Build times (excluding pulling of base image) on 18-core workstation::

- `vrtlmod-dev`: `t.b.d.`
- `vrtlmod-base`: `t.b.d.`

Image sizes::

- `vrtlmod-dev`: `t.b.d.`
- `vrtlmod-base`: `t.b.d.`

==== GitHub Action

Manual builds::

Use the `Run Workflow` button on https://github.com/tum-ei-eda/vrtlmod/actions/workflows/container.yml to build images for a specific OS.

CI Setup for DockerHub::

If you want to use the actions on a fork, they will fail due to missing docker credentials. Please export the following variables via `Settings -> Secrets -> Actions` to tell the jobs about your username and password:

- `DOCKER_PASSWORD`
- `DOCKER_USERNAME` (e.g., `tumeda`)
- `DOCKER_REGISTRY` (e.g., `docker.io`, `ghcr.io`)
- `DOCKER_NAMESPACE` (e.g., `tumeda`, `path/to/container`)

=== Running the Images in Docker Containers

To use the previously built or pulled images, run the following commands::

[,bash]
----
# pull a latest image:
docker pull tumeda/vrtlmod-base:latest-default-debian-stable

# run the pulled container and mount the host's vrtlmod repo:
cd path/to/vrtlmod/clone
docker run -it --rm -v $(pwd):$(pwd) -v .:/vrtlmod tumeda/vrtlmod-base:latest-default-debian-stable

# in the container:
/vrtlmod-install/bin/vrtlmod --version # <-- is the vrtlmod binary
----